name: Build Gradle project

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Cache konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
      - name: Run build with Gradle Wrapper
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: print artifacts
        run: ls -Rla build/classes
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: build
